version: '2.3'

x-rnode:
  &default-rnode
  image: $RNODE_IMAGE
  user: root
  restart: always

services:

  boot:
    << : *default-rnode
    container_name: boot
    command: run -s --validator-private-key $VALIDATOR_BOOT_PRIVATE --allow-private-addresses --host boot
              --protocol-port 40400 --discovery-port 40404
              --wallets-file /data-init/genesis/wallets.txt --bonds-file /data-init/genesis/bonds.txt
              --tls-certificate-path /data-init/node.certificate.pem --tls-key-path /data-init/node.key.pem
              --approve-duration 10seconds --approve-interval 10seconds
              --dev-mode
    ports:
    - $MY_NET_IP:40401:40401
    - $MY_NET_IP:40402:40402
    - $MY_NET_IP:40403:40403
    - $MY_NET_IP:40405:40405
    # Ports exposed externally
    - $MY_NET_IP:40400:40400
    - $MY_NET_IP:40404:40404
    volumes:
    - ./data-init/rnode:/data-init
    - ./data/rnode:/var/lib/rnode # expose RNode data-dir to host

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    ports:
    - $MY_NET_IP:5672:5672
    volumes:
    - ./data-init/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
